name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: prototipo_test
      id: prototipo_test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: prototipo_test
        setup-command: ''
        command: "./ejercicio1_test.py"
        input: ''
        expected-output: ''
        comparison-method: exact
        timeout: 5
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PROTOTIPO_TEST_RESULTS: "${{steps.prototipo_test.outputs.result}}"
      with:
        runners: prototipo_test
